version: "3.8"

services:
  backend:
    image: dthakurani/backend:final
    ports:
      - 2003:2003
    env_file:
      - .env

  frontend:
    build: dthakurani/frontend:final-1
    ports:
      - 8000:80
    depends_on:
      - backend
